import type { TextStats } from '@/features/text/types'

export class ReportExporter {
  static exportAsMarkdown(text: string, stats: TextStats): string {
    const report = `# Text Analysis Report
Generated by Texty 2.0 • ${new Date().toLocaleDateString()}

---

## Original Text
\`\`\`
${text}
\`\`\`

---

## Basic Statistics
| Metric | Value |
|--------|-------|
| Words | ${stats.words.toLocaleString()} |
| Unique Words | ${stats.uniqueWords.toLocaleString()} |
| Characters | ${stats.characters.toLocaleString()} |
| Sentences | ${stats.sentences} |
| Paragraphs | ${stats.paragraphs} |
| Avg Word Length | ${stats.avgWordLength} |
| Reading Time | ${stats.readingTime}m |

---

## Readability Scores
| Formula | Score | Description |
|---------|-------|-------------|
| **Flesch Reading Ease** | ${stats.readability.flesch} | ${stats.readability.fleschGrade} |
| **Gunning Fog Index** | ${stats.readability.gunningFog} | Years of education needed |
| **SMOG Index** | ${stats.readability.smog} | Simple Measure of Gobbledygook |
| **Coleman-Liau** | ${stats.readability.colemanLiau} | Based on characters |
| **Automated Readability** | ${stats.readability.automatedReadability} | ARI Score |

---

## Writing Style Analysis
| Metric | Value |
|--------|-------|
| **Tone** | ${stats.writingStyle.toneIndicator.toUpperCase()} |
| **Passive Voice** | ${stats.writingStyle.passiveVoicePercentage}% |
| **Adverb Count** | ${stats.writingStyle.adverbCount} |
| **Complex Sentences** | ${stats.writingStyle.complexSentencePercentage}% |
| **Avg Sentence Length** | ${stats.writingStyle.avgSentenceLength} words |

---

## SEO Analysis
**Overall SEO Score:** ${stats.seoScore}/100

### Keyword Density (Top ${Math.min(15, stats.keywordDensity.length)})
| Keyword | Count | Density | Status |
|---------|-------|---------|--------|
${stats.keywordDensity
  .map(
    (kw) =>
      `| ${kw.word} | ${kw.count} | ${kw.density.toFixed(2)}% | ${kw.status === 'optimal' ? '✓ Optimal' : kw.status === 'warning' ? '⚠ Warning' : '✗ Critical'} |`
  )
  .join('\n')}

---

## Top Keywords
${stats.keywords.map((kw) => `- ${kw}`).join('\n')}

---

*Generated with Texty 2.0 - Modern Text Processor*
`
    return report
  }

  static exportAsHTML(text: string, stats: TextStats): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Text Analysis Report - Texty 2.0</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 900px;
      margin: 0 auto;
      padding: 40px 20px;
      background: #f9f9f9;
    }
    .container {
      background: white;
      padding: 40px;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    h1 { font-size: 2em; margin-bottom: 10px; color: #111; }
    h2 { font-size: 1.5em; margin: 30px 0 15px; color: #333; border-bottom: 2px solid #000; padding-bottom: 5px; }
    .meta { color: #666; margin-bottom: 30px; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background: #f5f5f5; font-weight: 600; }
    .text-box { background: #f9f9f9; padding: 20px; border-radius: 4px; margin: 15px 0; white-space: pre-wrap; font-family: monospace; font-size: 0.9em; }
    .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 0.85em; font-weight: 600; }
    .badge-optimal { background: #d4edda; color: #155724; }
    .badge-warning { background: #fff3cd; color: #856404; }
    .badge-critical { background: #f8d7da; color: #721c24; }
    .badge-tone { background: #e7f3ff; color: #004085; padding: 6px 12px; }
    .score-badge { font-size: 2em; font-weight: bold; color: #28a745; }
    .keywords { display: flex; flex-wrap: wrap; gap: 8px; margin: 15px 0; }
    .keyword-tag { background: #000; color: #fff; padding: 6px 12px; border-radius: 4px; font-size: 0.85em; font-weight: 600; }
    .footer { text-align: center; margin-top: 40px; color: #666; font-size: 0.9em; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Text Analysis Report</h1>
    <p class="meta">Generated by Texty 2.0 • ${new Date().toLocaleString()}</p>

    <h2>Original Text</h2>
    <div class="text-box">${this.escapeHtml(text)}</div>

    <h2>Basic Statistics</h2>
    <table>
      <tr><th>Metric</th><th>Value</th></tr>
      <tr><td>Words</td><td>${stats.words.toLocaleString()}</td></tr>
      <tr><td>Unique Words</td><td>${stats.uniqueWords.toLocaleString()}</td></tr>
      <tr><td>Characters</td><td>${stats.characters.toLocaleString()}</td></tr>
      <tr><td>Sentences</td><td>${stats.sentences}</td></tr>
      <tr><td>Paragraphs</td><td>${stats.paragraphs}</td></tr>
      <tr><td>Avg Word Length</td><td>${stats.avgWordLength}</td></tr>
      <tr><td>Reading Time</td><td>${stats.readingTime}m</td></tr>
    </table>

    <h2>Readability Scores</h2>
    <table>
      <tr><th>Formula</th><th>Score</th><th>Description</th></tr>
      <tr><td><strong>Flesch Reading Ease</strong></td><td>${stats.readability.flesch}</td><td>${stats.readability.fleschGrade}</td></tr>
      <tr><td><strong>Gunning Fog Index</strong></td><td>${stats.readability.gunningFog}</td><td>Years of education needed</td></tr>
      <tr><td><strong>SMOG Index</strong></td><td>${stats.readability.smog}</td><td>Simple Measure of Gobbledygook</td></tr>
      <tr><td><strong>Coleman-Liau</strong></td><td>${stats.readability.colemanLiau}</td><td>Based on characters</td></tr>
      <tr><td><strong>Automated Readability</strong></td><td>${stats.readability.automatedReadability}</td><td>ARI Score</td></tr>
    </table>

    <h2>Writing Style Analysis</h2>
    <table>
      <tr><th>Metric</th><th>Value</th></tr>
      <tr><td>Tone</td><td><span class="badge badge-tone">${stats.writingStyle.toneIndicator.toUpperCase()}</span></td></tr>
      <tr><td>Passive Voice</td><td>${stats.writingStyle.passiveVoicePercentage}%</td></tr>
      <tr><td>Adverb Count</td><td>${stats.writingStyle.adverbCount}</td></tr>
      <tr><td>Complex Sentences</td><td>${stats.writingStyle.complexSentencePercentage}%</td></tr>
      <tr><td>Avg Sentence Length</td><td>${stats.writingStyle.avgSentenceLength} words</td></tr>
    </table>

    <h2>SEO Analysis</h2>
    <p><strong>Overall SEO Score:</strong> <span class="score-badge">${stats.seoScore}/100</span></p>

    <h3>Keyword Density (Top ${Math.min(15, stats.keywordDensity.length)})</h3>
    <table>
      <tr><th>Keyword</th><th>Count</th><th>Density</th><th>Status</th></tr>
      ${stats.keywordDensity
        .map(
          (kw) => `
      <tr>
        <td>${kw.word}</td>
        <td>${kw.count}</td>
        <td>${kw.density.toFixed(2)}%</td>
        <td><span class="badge badge-${kw.status}">${kw.status === 'optimal' ? '✓ Optimal' : kw.status === 'warning' ? '⚠ Warning' : '✗ Critical'}</span></td>
      </tr>`
        )
        .join('')}
    </table>

    <h2>Top Keywords</h2>
    <div class="keywords">
      ${stats.keywords.map((kw) => `<span class="keyword-tag">${kw.toUpperCase()}</span>`).join('')}
    </div>

    <div class="footer">
      <p>Generated with <strong>Texty 2.0</strong> - Modern Text Processor</p>
    </div>
  </div>
</body>
</html>`
  }

  private static escapeHtml(text: string): string {
    const div = document.createElement('div')
    div.textContent = text
    return div.innerHTML
  }

  static downloadMarkdown(text: string, stats: TextStats): void {
    const markdown = this.exportAsMarkdown(text, stats)
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
    this.downloadBlob(blob, 'texty-report.md')
  }

  static downloadHTML(text: string, stats: TextStats): void {
    const html = this.exportAsHTML(text, stats)
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
    this.downloadBlob(blob, 'texty-report.html')
  }

  private static downloadBlob(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob)
    const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, '-')
    const finalFilename = filename.replace(/\.(md|html)$/, `-${timestamp}.$1`)

    const a = document.createElement('a')
    a.href = url
    a.download = finalFilename
    a.style.display = 'none'
    document.body.appendChild(a)
    a.click()

    setTimeout(() => {
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    }, 100)
  }

  static copyMarkdownToClipboard(text: string, stats: TextStats): Promise<void> {
    const markdown = this.exportAsMarkdown(text, stats)
    return navigator.clipboard.writeText(markdown)
  }
}
